### PR TITLE
Use singledispatch for op_iter, op_len and create_operation_expression

### PR DESCRIPTION
**Pull request by skirpichev**
From the code it seems you reinvent functools.singledispatch.  Probably, this worth using it.

### CODE REVIEW

**Comment by wheerd** [comment]
Looks good, but possibly breaks existing code that relies on the existing API. It would be awesome if you could add a backward port for that :)

**Comment by henrik227** [comment]
@skirpichev You are making a good point with the versioning. I'm using MatchPy for another project, and I wouldn't want the API to change just like that.

@wheerd It's kind of off-topic, but is there a reason why we still use 0.x? The core functionality of MatchPy seems to be very reliable.

**Comment by skirpichev** [comment]
@henrik227, besides 0.x versioning, it's also not clear if undocumented functions are part of API.

**Comment by wheerd** [comment]
There is a couple of users (like sympy) who might be using these. The general idea of those functions to integrate MatchPy with existing data structures without having to change them (i.e. a third party package).

@henrik227 There is not really a reason not to have a 1.x version. I just didn't think the API was done/complete when I finished the thesis.

**Comment by skirpichev** [comment]
@wheerd, sorry for repeating, do you suggest adding register_operation_* functions, which will emit DeprecationWarning's, correct?

> I just didn't think the API was done/complete

Do you think it's complete now?  There is a lot of functions/methods, which aren't documented.

**Comment by wheerd** [comment]
@skirpichev just that is what I had in mind. In terms of completion, @henrik227 will have to answer that. I am not planning to add additional functionality to MatchPy, i.e. from my point of view, the API is stable. But since Henrik is the main user, he might want to change/extend it.

**Comment by skirpichev** [comment]
On Tue, Nov 20, 2018 at 02:24:05AM -0800, Henrik Barthels wrote:
>    Do you have an example of what changes from the user's perspective? If
>    it's just a different function call to do the same thing, I wouldn't worry
>    about backward compatibility.

It's not just a different function call, it's a different approach to
integrate user types to the matchpy framework.  All register_* functions
from matchpy/expressions/functions.py right now emulate nothing more
then a bunch of generic functions, where implementation choosen based
on the first argument.  Exactly what functools.singledispatch do.

So, for example, to work with dict currently we should register
a custom iterator like this:
register_operation_iterator(dict, lambda d: d.items())
Note, that third argument was left with the default value.

Using singledispatch here make things more explicit.  You will
just add a custom version of the op_iter interface for dict type:

@op_iter.register(dict)
def _(operation):
    return iter(operation.items())

Probably, it's possible to offer some compatibility wrappers
to emulate old interfaces (register_* functions), which would produce
warnings and so on.  Please decide if I should do.

**Comment by henrik227** [comment]
Thank you! 

> Probably, it's possible to offer some compatibility wrappers to emulate old interfaces (register_* functions), which would produce warnings and so on. Please decide if I should do.

No, I would say that's not necessary. I'm fine with just changing it. As you said, it's not a documented part of the API, and this is still a 0.x version.

**Pull request merged**
